DROP TABLE IF EXISTS shoes;

CREATE TABLE shoes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL ,
    content TEXT NOT NULL
)
